#!/usr/bin/env bash

issue_type="$1"
commit_message="$2"

issue_type="$(tr '[:lower:]' '[:upper:]' <<< ${issue_type:0:1})${issue_type:1}"

task_id=$(git rev-parse --abbrev-ref HEAD | grep -o "^[A-Z]*-[0-9]*")
if [ -z "$task_id" ]
then
    git commit -m "$issue_type: $commit_message"
else
    git commit -m "$issue_type: $commit_message #$task_id"
fi